### ISSUE TITLE
Error: "Server under pressure"

### ISSUE THREAD

**Issue by riefsdahl** [directus-labs/directus-template-cli#77]
After setting up Directus, I've attempted to run 'npx directus-template-cli@latest apply' in order to apply the AgencyOS template. However after selecting the template, entering my URL and access token I get the following output:

> === Applying template - AgencyOS to [url]
> 
> Loading 76 collections and 700 fields... done
> Loading 176 relations... done
> Loading 4 roles... done
> Loading 5 policies... done
> Loading 415 permissions... done
> Loading 5 users... done
> Loading 5 accesses... done
> Loading 17 folders... done
> -- Server under pressure. Retrying after 5000ms
> -- Retrying job (attempt 1)
> -- Server under pressure. Retrying after 5000ms
> -- Retrying job (attempt 1)
> -- Server under pressure. Retrying after 5000ms
> -- Retrying job (attempt 1)
> -- Server under pressure. Retrying after 5000ms
> -- Retrying job (attempt 1)

Even after waiting a long time it just keeps on retrying without any success.

The error logs in "/.directus/.directus-template-cli/logs" unfortunately don't contain any information except "Log started at 2025-03-10T03-28-01-306Z".

I've checked my server utilization and everything looks fine (meaning neither my CPU nore memory usage are anywhere near full capacity). I'm using Ubuntu 22.04.5 LTS in case this might be relevant.

Content of my docker-compose.yaml file:

```
version: '3'
services:
  database:
    image: mysql:8.0
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    ports:
      - 3307:3306
    volumes:
      - ./data/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '[password]'
      MYSQL_USER: '[user]'
      MYSQL_PASSWORD: '[password]'
      MYSQL_DATABASE: '[db]'
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
  cache:
    image: redis:6
  directus:
    image: directus/directus:11.5.1
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    depends_on:
      database:
        condition: service_healthy
    environment:
      KEY: '[key]'
      SECRET: '[secret]'
      DB_CLIENT: 'mysql'
      DB_HOST: 'database'
      DB_PORT: '3306'
      DB_DATABASE: '[db]'
      DB_USER: '[user]'
      DB_PASSWORD: '[password]'
      CACHE_ENABLED: 'false'
      CACHE_STORE: 'redis'
      REDIS: 'redis://cache:6379'
      ADMIN_EMAIL: '[email]'
      ADMIN_PASSWORD: '[password]'
      # These is helpful for local developement but should probably be removed in production
      # CORS_ENABLED: 'true'
      # REFRESH_TOKEN_COOKIE_DOMAIN: 'localhost'
      # EXTENSIONS_AUTO_RELOAD: 'true'
      WEBSOCKETS_ENABLED: 'true'
      # The default config prevents importing files from 0.0.0.0. See https://docs.directus.io/self-hosted/config-options.html#security . This can be removed in production but in local development it is recommended to keep it so you can import logos from Organization > website.
      IMPORT_IP_DENY_LIST: ''
      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      PUBLIC_URL: '[url]'
```

Are there any methods to get more detailed error logs or common troubleshooting steps I should try? Any help would be greatly appreciated.

**Comment by bryantgillespie** [comment]
You're hitting the pressure limiter on your instance. Usually not an issue on development workloads, but that depends on your hardware obviously.

Here's the docs that cover the config settings for it.
https://directus.io/docs/configuration/security-limits#pressure-based-rate-limiter

You can choose to turn it off if you want or dial back the settings a bit.

**Comment by riefsdahl** [comment]
> You're hitting the pressure limiter on your instance. Usually not an issue on development workloads, but that depends on your hardware obviously.
> 
> Here's the docs that cover the config settings for it. https://directus.io/docs/configuration/security-limits#pressure-based-rate-limiter
> 
> You can choose to turn it off if you want or dial back the settings a bit.

Thanks for the help. I've now used the provided default docker-compose.yaml file and otherwise only added the following lines:

```
RATE_LIMITER_ENABLED: 'false'
RATE_LIMITER_GLOBAL_ENABLED: 'false'
RATE_LIMITER_REGISTRATION_ENABLED: 'false'
PRESSURE_LIMITER_ENABLED: 'false'
```

However it still doesn't work, even on a new Hetzner cloud server I set up to test this. Apologies if I'm missing something obvious, would I have to otherwise configure the Docker container to have sufficient ressources available?

**Comment by bryantgillespie** [comment]
What are the specs of the server you've provisioned?

If you've turned off the pressure limiter and the rate limiter and you are still receiving the same error that seems very weird indeed.

**Comment by riefsdahl** [comment]
Thanks again, really appreciate the help. I've set up the Hetzner 'CCX13' cloud server plan:

- 2 dedicated vCPU
- 8 GB RAM
- 80 GB NVMe SSD

While just testing this again, applying the AgencyOS template actually did work at one point for some reason:

![Image](https://github.com/user-attachments/assets/37ad1bfe-deb9-43e5-9e25-50cdf332c763)

However afterwards I naively removed this instance again in order to make sure applying the AgencyOS template now works (also since there were still errors related to 'Request Entity Too Large' and 'Invalid foreign key for field "directus_files_id"' displayed as shown in the above screenshot) and got the previous 'Server under pressure' again:

![Image](https://github.com/user-attachments/assets/a58df627-6c3b-443a-b34d-dd87c4e00e67)

Afterwards I retried the process multiple times to make sure there's no factor of randomness or such resulting in the same errors again without any luck. What stands out to me is that when applying the template generally worked, the output while 'Loading 49 files' shows that after the first 'Request failed' it immediately proceeded with 'attempt 2' while also increasing the timeout in milliseconds (as opposed to the behaviour I experience otherwise where 'Retrying job' is done multiple times for each 'attempt' with the same timeout values of 5000ms). Seemingly indicating that the issue might be related to the pressure limiter actually not being disabled if I'd have to guess.

Here's also the entire docker-compose.yaml file I've used (both when it worked and most recently didn't work):

```
version: '3'
services:
  database:
    image: postgis/postgis:13-master
    ports:
      - 5432:5432
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: '[user]'
      POSTGRES_PASSWORD: '[password]'
      POSTGRES_DB: '[db]'

  cache:
    image: redis:6

  directus:
    image: directus/directus:11.5.1
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    depends_on:
      - cache
      - database
    environment:
      KEY: '[key]'
      SECRET: '[secret]'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: '[db]'
      DB_USER: '[user]'
      DB_PASSWORD: '[password]'

      CACHE_ENABLED: 'false'
      CACHE_STORE: 'redis'
      REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: '[email]'
      ADMIN_PASSWORD: '[password]'

      CORS_ENABLED: 'true'
      REFRESH_TOKEN_COOKIE_DOMAIN: 'localhost'
      EXTENSIONS_AUTO_RELOAD: 'true'

      WEBSOCKETS_ENABLED: 'true'
      IMPORT_IP_DENY_LIST: ''

      # Rate limiter adjustments
      RATE_LIMITER_ENABLED: 'false'
      RATE_LIMITER_GLOBAL_ENABLED: 'false'
      RATE_LIMITER_REGISTRATION_ENABLED: 'false'
      PRESSURE_LIMITER_ENABLED: 'false'

      PUBLIC_URL: '[url]'
```

In case this issue hasn't been brought up by others I assume it might be related to my specific setup and I don't expect you to assist with further troubleshooting given this is a open source application. If you think it's worth inspecting further I'm happy to provide any relevant logs or try other steps though of course. Either way thanks a lot for your work.
